version: "3.8"
services:
  Kaddem:
    container_name: Kaddem
    build: ../5TWIN6-G1-KADDEM-DevOps
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/kaddemApp?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    image: azizbenismail/kaddem:9
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:5.7
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql



volumes:
  db:
